### ISSUE TITLE
Spremembe za header

### ISSUE THREAD

**Issue by mihavidakovic** [mihavidakovic/testis#9]
@tipmisle nared da k poscrollaš za več kokr 600px dol, da se dodata elementu <nav> (al pa elementu s klaso .navbar) klasi .bg pa .fixed.

tnx.

**Comment by mihavidakovic** [comment]
pač vem da se da hitr z jqueryom to narest, ampak izziv zate da nardiš z javascriptom

**Comment by tipmisle** [comment]
@mihavidakovic bog narejeno je. neodgovorjene issues ne popravljam. hec <3
